version: '3.9'

services:

  # API Container
  backend:
    image: bennodev19/dronies-watch-backend:latest
    container_name: 'dronies-watch-backend'
    restart: always
    env_file:
      - .env.backend
    depends_on:
      - db
    ports:
      - '5000:9000'

  # Database Container
  db:
    image: 'postgres:latest'
    container_name: 'dronies-watch-db'
    restart: always
    env_file:
      - .env.db
    ports:
      - '5001:5432'
    volumes:
      - './.volumes/db-data:/varlib/postgresql/data'

  # Allows us to update the running version of the containerized app
  # simply by pushing a new image to the Docker Hub
  # https://github.com/containrrr/watchtower
  # https://www.youtube.com/watch?v=5lP_pdjcVMo
  watchtower:
    image: 'containrrr/watchtower'
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: --cleanup --interval 300 # Checks for updates for all running Containers every 5min (300s)
