name: Release
on:
  push:
    branches:
      - master
    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
    paths:
      - "server/**"
      - ".github/workflows/**"

jobs:
  build-and-deploy-backend:
    name: 🛠 Build Backend Image for Prod & Push to Dockerhub
    runs-on: ubuntu-latest
    steps:
      # Checkout Project
      - name: 📚 Checkout
        uses: actions/checkout@v2

        # Setup Docker Builder
        # -> The tool we are going to build our Docker Image
        # https://github.com/marketplace/actions/docker-setup-buildx
      #      - name: 🐳 Set up Docker Buildx
      #        id: buildx
      #        uses: docker/setup-buildx-action@v1

      - name: 🐳 Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        # https://github.com/marketplace/actions/build-and-push-docker-images
        # https://www.docker.com/blog/docker-v2-github-action-is-now-ga/
      - name: 🐳 Build and push Docker Image to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: server/Dockerfile # Path to the Dockerfile from which to build the Docker Image from (default {context}/Dockerfile)
          #          builder: ${{ steps.buildx.outputs.name }}
          push: true
          # https://github.com/docker/build-push-action/issues/449
          # https://github.com/docker/build-push-action/issues/422#issuecomment-889352615
          # https://github.com/docker/buildx/issues/681#issuecomment-934211900
          no-cache: true
          tags: latest # Tag the build with the 'latest' tag (Docker Tags are like tags on GitHub, to differentiate between versions of the same Repository)

        # https://www.mikenewswanger.com/posts/2020/docker-image-digests/#:~:text=Docker%20digest%20is%20provided%20as,based%20on%20the%20image%20build.
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
